### PR TITLE
Add crawler redis pagecount filter

### PR DESCRIPTION
**Pull request by devspyrosv**
Add a redis filter that limits the crawled pages for a particular spider,domain,crawlid combination.

_This filter is influenced by github's user kazuar pull request._

The fix for crawler/tests/online.py is also included in this commit.

### CODE REVIEW

**Comment by madisonb** [comment]
Can you leave a comment on how to directly test this? If I have a cluster spun up, what are the steps I should take to verify this PR? The code looks good on first glance but it would be nice to have a series of commands to verify this.

**Comment by devspyrosv** [comment]
What I did was:

1. Set PAGE_PER_DOMAIN_LIMIT to something small say 100
2. Let PAGE_PER_DOMAIN_LIMIT_TIMEOUT to its default for the first trial.
3.1 Start a crawler with LOG_ENABLED = True in localsettings.py
3.2 Start kafkadump (of course have a redis-monitor and a kafka-monitor running)
4. Feed a crawl with ```python kafka_monitor.py feed '{"url": "http://edition.cnn.com", "allowed_domains":["edition.cnn.com"], "appid":"crawler", "crawlid":"newsitems", "maxdepth":2}'``` with maxdepth enough to find those 100 pages and most importantly even more.
5. Let the crawl run and wait for the last message of kafkadump. Wait a bit longer and scrapy will announce how many pages it parsed. They must be less or equal to 100.
6. If you have a phpredisadmin installation available, you can get visual feedback from the queue key and the new keys that were added with this commit.

**Comment by devspyrosv** [comment]
To check again you will have to wait for the TTL to expire or you can delete the redis key.

**Comment by madisonb** [comment]
Original Reference PR: #107

**Comment by devspyrosv** [comment]
I added the ability to override the global PAGE_PER_DOMAIN_LIMIT when submitting an API crawl request by adding the new argument 'maxpages'.

**Comment by devspyrosv** [comment]
There are two separate methods of limiting the number of scraped pages per domain. 
One is through the crawler's settings which enforces a hard global limit for all the domains (individually) and the other is a limit set through the kafka API which is taken into account only for the crawl jobs that have it as an argument.

**Pull request merged**
