### PR TITLE
Update Crawler, Kafka-Monitor, Redis-Monitor requirements

### PR DESCRIPTION
**Pull request by devspyrosv**
**Update python requirements** for:

- crawler
- kafka-monitor
- redis-monitor

Tested using python3.5.3

### CODE REVIEW

**Comment by madisonb** [comment]
One thing I need to do for this before I merge it in is to also test the `utils` example files - I recall there is a zookeeper_watcher bug/issue/problem with the latest kazoo library, but I don't recall what version of kazoo was needed.

Also this PR does not update the rest service requirements or the utils package requirements. These changes look fine for 3/5 components though.

**Comment by devspyrosv** [comment]
I updated the rest service today and some additions were needed in the online tests.
I am working on the utils package requirements. Thank you!

**Comment by devspyrosv** [comment]
I added updates to the rest service and to scutils package.

**Comment by zusrsoft** [comment]
Please give me a scrapy-cluster scrapy 1.5 version. Thank you

**Comment by zusrsoft** [comment]
[when pulling 8ea8e66 on devspyrosv ]


test_ping (__main__.TestZookeeperWatcher) ... No handlers could be found for logger "kazoo.client"
ERROR
test_get_file_contents (__main__.TestZookeeperWatcher) ... ERROR

======================================================================
ERROR: test_ping (__main__.TestZookeeperWatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 384, in setUp
    self.zoo_client.start()
  File "/home/dt/.local/lib/python2.7/site-packages/kazoo/client.py", line 567, in start
    raise self.handler.timeout_exception("Connection time-out")
KazooTimeoutError: Connection time-out

======================================================================
ERROR: test_get_file_contents (__main__.TestZookeeperWatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 384, in setUp
    self.zoo_client.start()
  File "/home/dt/.local/lib/python2.7/site-packages/kazoo/client.py", line 567, in start
    raise self.handler.timeout_exception("Connection time-out")
KazooTimeoutError: Connection time-out

======================================================================
FAIL: test_roll_uniques (__main__.TestStatsUniqueCounter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 282, in test_roll_uniques
    self.assertEqual(counter.value(), 10)
AssertionError: 6 != 10

----------------------------------------------------------------------
Ran 20 tests in 96.731s

FAILED (failures=1, errors=2)
utils tests failed

**Comment by madisonb** [comment]
Closing in favor of #185

**Pull request closed without merging**
