### PR TITLE
Made ansible script CentOS 7 compatible

### PR DESCRIPTION
**Pull request by knirbhay**
The default ansible script was failing to install in CentOS 7 vagrant machine. So I fixed the deployment script. Tested with vagrant. It is up and running.

### CODE REVIEW

**Comment by knirbhay** [comment]
Looks like build. Let me run the tests again.

**Comment by knirbhay** [comment]
There you go.

**Comment by madisonb** [comment]
This is great work! Two comments:

a) As outlined [here](http://scrapy-cluster.readthedocs.io/en/latest/topics/contributing.html#submitting-pull-requests), can you please submit your PR to the `dev` branch instead of the `master` branch? Master is reserved for release code only and Dev is where all the latest work happens within this project.

b) Is there a way we can run automated tests for this using Travis CI? I see the build passed but Travis Builds an Ubuntu VM and I would like some sanity to test that CentOS is working too.

Otherwise the code looks good and I will wait to hear back from you.

**Comment by knirbhay** [comment]
Sure, will send the PR to dev branch later when my fork goes green in Travis with centos with all offline and online tests working and I will also share the results.

**Comment by madisonb** [comment]
Feel free to continue to get this working by adding more commits. Sometimes it takes me a while too to get Travis builds correct! I assume you are following one of the guides outlined at some of the top google search results like:

http://stackoverflow.com/a/32985138
http://bertvv.github.io/notes-to-self/2015/12/11/testing-ansible-roles-with-travis-ci-part-1-centos/
https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/

**Comment by knirbhay** [comment]
Yeap.. I am following 2nd link that you have shared. I was able to run ansible steps. Now I am trying to run offline and online tests. I am close :) . Thanks for the help. Will do it over weekends.

**Comment by knirbhay** [comment]
It looks like when docker mounts the source code folder inside the container mounted folder becomes read-only. I am trying to figure out a way to make it writable. 

```
======================================================================
ERROR: test_preserve_extra (__main__.TestLogJSONFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests_offline.py", line 174, in setUp
    file='test.log')
  File "/root/sc/local/lib/python2.7/site-packages/scutils/log_factory.py", line 87, in __init__
    backupCount=backups)
  File "/root/sc/local/lib/python2.7/site-packages/cloghandler.py", line 136, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/root/sc/local/lib/python2.7/site-packages/cloghandler.py", line 165, in _open
    stream = open(self.baseFilename, mode)
IOError: [Errno 30] Read-only file system: '/root/scrapy-cluster/utils/test.log'
----------------------------------------------------------------------
```

**Comment by knirbhay** [comment]
Work is done. How do I transfer this PR to dev branch. Should I raise a new PR after closing this?

**Comment by knirbhay** [comment]
Raised a new PR https://github.com/istresearch/scrapy-cluster/pull/67

**Pull request closed without merging**
