### PR TITLE
PEP8 compliance and some other cleanups

### PR DESCRIPTION
**Pull request by tarhan**

### CODE REVIEW

**Comment by madisonb** [comment]
What tool did you use to format everything? I always use Sublime but obviously it lets you get away with a lot more stuff.

Interesting that the build failed, I presume I need to add a flag [here](https://github.com/istresearch/scrapy-cluster/blob/dev/travis/docker.sh#L26) to check if it also is a PR so it does not try to push to docker hub with invalid creds.

Otherwise my last note is Why did coverage go down? I understand there are typos and some PEP8 formatting, but I would presume coverage would remain the same. Thoughts? I will have to look at the coverage reports for these files:
* kafka-monitor/kafka_monitor.py
* crawler/crawling/spiders/wandering_spider.py
* redis-monitor/plugins/base_monitor.py
* crawler/crawling/spiders/link_spider.py

as those appear to be the ones who went down.

**Comment by tarhan** [comment]
I'm using PyCharm mainly  because its embedded debugger and intellisense features.
Former allows me to debug Python apps like any compiled apps even on remote hosts (other hosts or inside Docker). So it is very good for if I need to do step by step debugging for app contained inside Docker container.  
Latter can be archived for Sublime with [Anaconda plugin](https://github.com/DamnWidget/anaconda). But at time I used it I failed to do its correct configuration for its linter and intellisense. It very often hangs whole Sublime. I'm not sure how its working now.  
PyCharm's **inspections** feature allows me to not only to find PEP8 and other warnings but also do automatic corrections where it is possible.  



Yeah, because you pass ```DOCKER_USERNAME``` and ```DOCKER_PASSWORD``` only for your builds.  

As for coverage I'm not sure. I will investigate it

**Comment by madisonb** [comment]
Any update as to why coverage dropped?

**Comment by madisonb** [comment]
Closing for now.

**Pull request closed without merging**
