### PR TITLE
Add python 3 support.

### PR DESCRIPTION
**Pull request by gas1121**
Use **decode_responses** option on Redis client and **value_deserializer**,**value_serializer** option on Kafka client to handle unicode problem. Also fix several syntax error and update several test cases for python 3. And as scrapy-cluster 1.2 use ujson instead of pickle, I think no migration is needed.

### CODE REVIEW

**Comment by madisonb** [comment]
Wow this is great! I had no idea I was actually so close to getting this project python 3 compatible, your changes make it seem so simple.

This has been a long standing feature request, and given that the travis build is 👍 the only thing I would like to do is some internal validation and run it myself - the code looks good.

Fixes #46

**Comment by gas1121** [comment]
fix #128 It is an unicode issue as **Kazoo** client requires and returns byte type value when using **get** and **set**. Also fix related tests and add an online test for ZookeeperWatcher.

**Comment by madisonb** [comment]
Newest changes also look good. The only thing I see missing here is that we may need to add naive os tests, since `./run_docker_test.sh` scripts don't actually test the `scutils` library offline/online tests (they only test the particular component). 

Its an older artifact from older versions of scrapy cluster, but in past we used the ansible roles to deploy and ensure the project could run on both native ubuntu and centos. In a perfect world, I would like to duplicate them but for python3.6 instead. Those ansible tests run the whole offline and online test suite, which would pick your changes.

That won't prevent me from merging this in though, but I may make a separate ticket to address it.

**Comment by madisonb** [comment]
If you run the utilities unit tests, both in python 2 and python 3 the unit tests fail at various stages. The `scutils` library is pretty critical for functionality across the project, so failing tests here means a project that becomes broken.

For python 2 (/utils):
```
$ nosetests -v --with-coverage --cover-erase # ok

$ python tests/online.py -r localhost -p 6379 # fails
test_fifo_queue (__main__.TestRedisFifoQueue) ... ERROR
test_priority_queue (__main__.TestRedisPriorityQueue) ... ERROR
```

For python 3 (/utils):
```
$ nosetests -v --with-coverage --cover-erase # fails
test_decode (test_redis_queue.TestBase) ... ERROR
test_encode (test_redis_queue.TestBase) ... FAIL

$ python tests/online.py -r localhost -p 6379 # fails
test_fifo_queue (__main__.TestRedisFifoQueue) ... ERROR
test_priority_queue (__main__.TestRedisPriorityQueue) ... ERROR
test_stack (__main__.TestRedisStack) ... ERROR
test_get_file_contents (__main__.TestZookeeperWatcher) ... Exception in thread Thread-30:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster-p36/lib/python3.6/site-packages/scutils/zookeeper_watcher.py", line 121, in init_connections
    self.update_file(self.my_file)
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster-p36/lib/python3.6/site-packages/scutils/zookeeper_watcher.py", line 216, in update_file
    self.update_pointed()
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster-p36/lib/python3.6/site-packages/scutils/zookeeper_watcher.py", line 245, in update_pointed
    watch=self.watch_pointed)
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster-p36/lib/python3.6/site-packages/kazoo/client.py", line 1026, in get
    return self.get_async(path, watch).get()
  File "/Users/madisonb/.local/share/virtualenvs/scrapy-cluster-p36/lib/python3.6/site-packages/kazoo/client.py", line 1036, in get_async
    raise TypeError("Invalid type for 'path' (string expected)")
TypeError: Invalid type for 'path' (string expected)
# did not get any further because the thread gets stuck
```

I triple checked and made sure I had the latest build from this PR as the `scutils` package installed in my virtualenv, can you reproduce what I am seeing?

**Comment by madisonb** [comment]
The important part here is [this](https://git.io/v7IpG) section of code that runs within the ansible travis tests. It not only uninstalls pypi scutils, but installs the bleeding edge source and then runs the full suite of offline and online unit tests. (of which we don't get in the docker suite tests)

This could be caught in a variety of ways:
1. Add a special docker container for running the `scutils` library only. Then we could use `./run_docker_tests.sh` and it would run the scutils unit tests and integration tests via our normal docker compose setup.
2. Add ubuntu/centos python 3 ansible roles. I think this is a worthwhile effort for folks who don't use docker, and would help ensure the native source code can run in normal environments as well.

Both 1 and 2 above seem like good ideas and would help catch nagging scutils library updates that may arise within this PR.

**Comment by gas1121** [comment]
I've merged the newest commit and my [travis build](https://travis-ci.org/gas1121/scrapy-cluster/builds/256725375) seems work fine. Also before I push my update I've passed all tests on my local docker environment.
Did you updated both code and tests and deleted all old test data in redis? Old redis data may also make tests fail.
I agree new travis test job for python 3 is needed. My work flow to test scutils on my local docker environment is similar with the first one and I think I can push an update about this.

**Comment by madisonb** [comment]
I have not been able to throw anything at this PR that did not pass all of my tests. I plan on merging this :crossed_fingers: tomorrow. Awesome work @gas1121!

**Comment by dag4202** [comment]
I'm just passing by. Is python 3 supported now? The README claims that python 2.7 is required.

**Pull request merged**
