### PR TITLE
Scrapy Cluster Test Enviornment

### PR DESCRIPTION
**Pull request by jasonrhaas**
This pull request includes a Vagrantfile and the associated Ansible code to make a pre-canned scrapy cluster VM.  Also added some info to the README on how to get set up.

### CODE REVIEW

**Comment by madisonb** [comment]
Can you reprovision your vagrant box and try this again as I cannot get Kafka to stand up consistently.

**Comment by madisonb** [comment]
We also probably don't need to store the miniconda.sh file, and should be pulled from the internet.

**Comment by jasonrhaas** [comment]
Added some code in Ansible to automatically reboot Kafka at the end of the provisioning process so it can cleanly connect with zookeeper.  Also removed Miniconda.sh and now pull from the internet.  I tested this with a brand new VM and followed the README to run the `run_online_tests.sh` and it worked flawlessly.

**Comment by madisonb** [comment]
Ah man... I had older `localsettings.py` files in all 3 folders with my old setup that had custom kafka/zookeeper/redis setups. So it was overwriting the defaults and therefore trying to look for a vm at an address that wasn't running when running the online tests. Arg.

This is good, merging.

**Pull request merged**
